openapi: 3.1.1
info:
  title: "API First"
  version: "1.0.0"
  description: "API Firts"
servers:
  - url: "http://localhost:3000"
components:
  schemas:
    HelloResponse:
      type: "object"
paths:
  /hello:
    get:
      summary: Hello World
      responses:
        "200":
          description: A successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/HelloResponse"
  /user:
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
              schema:
                type: object
                required:
                  - name
                  - age
                  - email
                properties:
                  name:
                    type: string
                    minLength: 2
                  age:
                    type: integer
                    minimum: 18
                  email:
                    type: string
                    format: email
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  age:
                    type: integer
                  email:
                    type: string
  /user/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '404':
          description: User not found
          content:
            application/json: